# Generated by Django 4.0.4 on 2022-05-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name/Description')),
                ('un_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Available Quantity')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0, verbose_name='Product Status')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity of product')),
                ('un_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Price of product')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of order')),
                ('requester', models.CharField(max_length=255, verbose_name='Requester of order')),
                ('postal_code', models.CharField(max_length=8, verbose_name='Postal Code / CEP')),
                ('uf', models.CharField(help_text='Federal Unity', max_length=2, verbose_name='UF')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('district', models.CharField(max_length=60, verbose_name='District')),
                ('address', models.CharField(help_text='First address line', max_length=300, verbose_name='Address')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('dispatcher', models.CharField(max_length=255, verbose_name='Dispatcher of order')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Delivered')], default=0, verbose_name='Order Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.product', verbose_name='Product')),
            ],
        ),
    ]
